title: Mohamed Abdella's Professional Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my professional portfolio. I am a Tax Accountant and Data Analyst skilled in utilizing advanced data tools to drive strategic decisions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Build settings
theme: minima
plugins:
  - jekyll-feed

# Include folders and files
include:
  - _projects
  - _skills
  - _education

# Collections
collections:
  power_bi_projects:
    output: true
  python_projects:
    output: true
  r_projects:
    output: true
  tableau_visualizations:
    output: true
  excel_projects:
    output: true
  sql_projects:
    output: true

# Social links
twitter_username: yourusername
github_username: yourgithub
linkedin_username: yourlinkedin

